spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/eshop
        username: postgres
        password: postgres
    flyway:
        url: jdbc:postgresql://localhost:5432/eshop
        user: postgres
        password: postgres
        locations: classpath:db/migration
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: mailsenderforproject11@gmail.com
        password: jnbzcvipxsaqupux
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
server:
    servlet:
        session:
            timeout: '300s'
loadPictureUrl: static/pictures/
targetPictureUrl: build/resources/main/static/pictures/





