spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/final_project
        username: postgres
        password: s63amg
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

server:
    servlet:
        session:
            timeout: '180s'

loadPictureUrl: static/pictures/
targetPictureUrl: build/resources/main/static/pictures/



